#!/bin/bash
dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd $dir
rm -rf LockstepClient/Assets/Plugins/Libs/*
rm -rf LockstepServer/Libs/*
cp -rf ./Libs/* LockstepClient/Assets/Plugins/Libs
cp -rf ./Libs/* LockstepServer/Libs
