#!/bin/bash
clear
dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd $dir
ps -ef | grep "Server.Lobby" | grep -v grep |awk '{print $2}' | xargs kill -9
ps -ef | grep "LSClient" | grep -v grep |awk '{print $2}' | xargs kill -9
open -n Build/LSClient.app
mono Server/bin/Server.Lobby.exe
