#!/bin/bash
dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd $dir
pwd
cp -rf ../../../Common/Libs/* Assets/Plugins/Libs
#rm -rf Assets/Plugins/Libs/LiteDB*

mv Assets/Plugins/Libs/Editor/* Assets/Plugins/Libs/
mv Assets/Plugins/Libs/*.Editor.* Assets/Plugins/Libs/Editor/
rm -rf Assets/Plugins/Libs/UnityE*.dll
rm -rf Assets/Plugins/Libs/UnityE*.mdb
rm -rf Assets/Plugins/Libs/UnityE*.xml
rm -rf Assets/Plugins/Libs/Entitas*.dll
rm -rf Assets/Plugins/Libs/Desperate*.dll
rm -rf Assets/Plugins/Libs/*Tank*
rm -rf Assets/Plugins/Libs/*Client*
rm -rf Assets/Plugins/Libs/*ECS*

mono ../../../bin/CopySourceFiles.exe ../Tools/Config/CopySourceFiles/Common2Tank.json