#!/bin/bash
clear
dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd $dir
ps -ef | grep "Server.Lobby" | grep -v grep |awk '{print $2}' | xargs kill -9
ps -ef | grep "LPClient.app" | grep -v grep |awk '{print $2}' | xargs kill -9
open -n Build/LPClient.app
mono ../../Server/bin/Server.Lobby.exe
